// packages/cli/fragments/fragment-next/src/pages/index.jsx
import { useState } from "react";
import { invoke } from "@tauri-apps/api/tauri";
import Image from "next/image";
import reactLogo from "../assets/react.svg";
import tauriLogo from "../assets/tauri.svg";
import nextLogo from "../assets/next.svg";

function App() {
  const [greetMsg, setGreetMsg] = useState("");
  const [name, setName] = useState("");

  async function greet() {
    setGreetMsg(await invoke("greet", { name }));
  }

  return (
    <div className="container">
      <h1>Welcome to Tauri!</h1>

      <div className="row">
        <span className="logos">
          <a href="https://nextjs.org" target="_blank">
            <Image
              width={144}
              height={144}
              src={nextLogo}
              className="logo next"
              alt="Next logo"
            />
          </a>
        </span>
        <span className="logos">
          <a href="https://tauri.app" target="_blank">
            <Image
              width={144}
              height={144}
              src={tauriLogo}
              className="logo tauri"
              alt="Tauri logo"
            />
          </a>
        </span>
        <span className="logos">
          <a href="https://reactjs.org" target="_blank">
            <Image
              width={144}
              height={144}
              src={reactLogo}
              className="logo react"
              alt="React logo"
            />
          </a>
        </span>
      </div>

      <p>Click on the Tauri, Next and React logos to learn more.</p>

      <div className="row">
        <div>
          <input
            id="greet-input"
            onChange={(e) => setName(e.currentTarget.value)}
            placeholder="Enter a name..."
          />
          <button type="button" onClick={() => greet()}>
            Greet
          </button>
        </div>
      </div>

      <p>{greetMsg}</p>
    </div>
  );
}

export default App;

// packages/cli/fragments/fragment-nuxt/src/pages/index.vue
<template>
  <div class="container">
    <h1>Welcome to Tauri!</h1>
    <div class="row">
      <span class="logos"
        ><a href="https://nuxt.com" target="_blank"
          ><img
            alt="Nuxt logo"
            src="~/assets/nuxt.svg"
            width="144"
            height="144"
            decoding="async"
            data-nimg="1"
            class="logo nuxt"
            style="color: transparent" /></a
      ></span>
      <span class="logos"
        ><a href="https://tauri.app" target="_blank"
          ><img
            alt="Tauri logo"
            src="~/assets/tauri.svg"
            width="144"
            height="144"
            decoding="async"
            data-nimg="1"
            class="logo tauri"
            style="color: transparent" /></a
      ></span>
      <span class="logos"
        ><a href="https://nuxt.com" target="_blank"
          ><img
            alt="Vue logo"
            src="~/assets/vue.svg"
            width="144"
            height="144"
            decoding="async"
            data-nimg="1"
            class="logo vue"
            style="color: transparent" /></a
      ></span>
    </div>
    <p>Click on the Tauri, Nuxt and Vue logos to learn more.</p>
    <div class="row">
      <input v-model="input" id="greet-input" placeholder="Enter a name..." />
      <button type="button" @click="runCommand">Greet</button>
    </div>
    <p>
      {{ output }}
    </p>
  </div>
</template>

<script>
export default {
  data() {
    return {
      input: "",
      output: "",
    };
  },
  methods: {
    async runCommand() {
      this.output = await this.$tauri.invoke("greet", { name: this.input });
    },
  },
};
</script>

<style>
.logo.nuxt:hover {
  filter: drop-shadow(0 0 2em #108775);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #41b883);
}
</style>
