// packages/cli/fragments/fragment-svelte-kit-ts/src/lib/Greet.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/tauri";

  let name = "";
  let greetMsg = "";

  async function greet() {
    // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
    greetMsg = await invoke("greet", { name });
  }
</script>

<div>
  <div class="row">
    <input id="greet-input" placeholder="Enter a name..." bind:value={name} />
    <button on:click={greet}> Greet </button>
  </div>
  <p>{greetMsg}</p>
</div>

// packages/cli/fragments/fragment-solid-start-ts/src/components/Greet.tsx
import {createSignal} from "solid-js";

export default function Greet() {
    const [greetMsg, setGreetMsg] = createSignal("");
    const [name, setName] = createSignal("");

    async function greet() {
        const {invoke} = await import("@tauri-apps/api/tauri");
        // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
        setGreetMsg(await invoke("greet", {name: name()}));
    }


    return (
        <>
            <div class="row">
                <div>
                    <input
                        id="greet-input"
                        onChange={(e) => setName(e.currentTarget.value)}
                        placeholder="Enter a name..."/>
                    <button type="button" onClick={() => greet()}>
                        Greet
                    </button>
                </div>
            </div>
            <p>{greetMsg}</p>
        </>
    );
}
